name: nomokitjr
version: 1.0.1+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
  usb_serial:
    git:
      url: https://github.com/jymden/usbserial.git
      ref: master
  url_launcher: ^6.1.11
  flutter_spinkit: ^5.2.0
  flutter_inappwebview: ^6.0.0
  http: ^0.13.6
  path_provider: ^2.0.15
  share_plus: ^7.0.1
  package_info_plus: ^8.1.1
  get_storage: ^2.1.1
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  file_picker: ^8.1.2
  cached_network_image: ^3.2.3
  in_app_update: ^4.0.4
  web_socket_channel: ^2.4.0
  restart_app: ^1.2.1
  dropdown_search: ^5.0.6
  dio: ^5.3.3
  fluttertoast: ^8.2.8
  http_parser: ^4.0.2
  rename_app: ^1.3.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/icon/logo.png"
  android: true
  ios: false

flutter:
  assets:
    - assets/img/
    - assets/icon/
    - assets/gui/
    - assets/gui/sounds/
    - assets/gui/chunks/
    - assets/gui/static/assets/
    - assets/gui/static/blocks-media/
    - assets/gui/static/blocks-media/extensions/
    - assets/gui/static/blocks-media/icons/
    - assets/gui/static/extensions/
  uses-material-design: true
